### ISSUE TITLE
Statement generator graphs do not appear to update 

### ISSUE THREAD

**Issue by jono-poltrack** [adlnet/xAPI-Workshop#11]
The graphs that are associated with the french toast course (created with the statement generator) do not seem to have any affect on the graph when reloaded.  

Ex. I used the generator to create a statement were the ingredients module was "launched", refreshed the graphs and they did not show the new data.  The data was available in the statement viewer but did not seem to change the graphs

**Comment by ljwolford** [comment]
now users have to add the context workshop context activity id whenever you create the statement. it should be storing that id in your local storage but in case it isn't, you can use: http://adlnet.gov/event/xapiworkshop/myworkshop as the id. it was broken up like this in case there were ever multiple workshops going on at the same time and you decided to launch the app so you could only see your results and not everyone's at the same time. i'll check the readmes if this step isn't added and will add it in.
