### ISSUE TITLE
Statement generator graphs - Number of launches compared to pages read

### ISSUE THREAD

**Issue by jono-poltrack** [adlnet/xAPI-Workshop#12]
Like in issue 11, this does not seem to update the number launches when I add them via the generator, but I'm also unsure on what we are showing in this last graph --

The old version of this graph had a bar for the "launched module", and then a bar for each "page read" in a module.  Now there is a single bar that show the number read.. but what is this total?  which page is this?  Can we show the number of read on each page as this shows how the granular content is actually being accessed.

Need to be able to represent stuff like >>

Intro module launched 3 times
Intro page 1 read 2 times (this one you can do in the current form)

Ingredients module launched 3 times
Ingredients page 1 read 2 times
Ingredients page 2 read 1 time
Ingredients page 3 read 0 times (this one you can not do in the current form)

etc...

**Comment by ljwolford** [comment]
see response on #11 for updating issue. this one shows the number of launches and reads for each module and it's children. so when it says 'ingredients' read X times, it's totaling the nested pages in that count. it would make most sense to add a child graph to those that would break out which nested pages are read/launch.

**Comment by ljwolford** [comment]
update - we use the native nv api to create the charts here since dashboard needs fixed/updated...child chart only exists in dashboard, is not native. need to fix those problems before updating this
